export const SET_BLOG_CONTENT = 'SET_BLOG_CONTENT'
export const SET_EDIT_BLOG_CONTENT = 'SET_EDIT_BLOG_CONTENT'
export const SET_BLOG_LIST = 'SET_BLOG_LIST'
export const SET_BLOG_LIST_LOADING = 'SET_BLOG_LIST_LOADING'

export const ADD_BLOG = 'ADD_BLOG'
export const ADD_BLOG_REQUEST = 'ADD_BLOG_REQUEST'
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS'
export const ADD_BLOG_FAILED = 'ADD_BLOG_FAILED'

export const UPDATE_BLOG = 'UPDATE_BLOG'
export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST'
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS'
export const UPDATE_BLOG_FAILED = 'UPDATE_BLOG_FAILED'



export const GET_ALL_BLOGS_REQUEST = 'GET_ALL_BLOGS_REQUEST'
export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS'
export const GET_ALL_BLOGS_FAILED = 'GET_ALL_BLOGS_FAILED'

export const GET_BLOG_REQUEST = 'GET_BLOG_REQUEST'
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS'
export const GET_BLOG_FAILED = 'GET_BLOG_FAILED'

export const GET_PROFILE_BLOGS_REQUEST = 'GET_PROFILE_BLOGS_REQUEST'
export const GET_PROFILE_BLOGS_SUCCESS = 'GET_PROFILE_BLOGS_SUCCESS'
export const GET_PROFILE_BLOGS_FAILED = 'GET_PROFILE_BLOGS_FAILED'